# Enable console logging.
console_logging: true

# Enable local (CSV) logging.
csv_logging: true

# Enable AbuseIPDB reporting.
abuseipdb_enable: false

# AbuseIPDB key for reporting.
abuseipdb_key: "AbuseIPDB API key goes here"

# Port the fake telnet server will listen on.
# Beware, the standard port (23) may require root access!
# Alternatively, you could use iptables to redirect 23 to the port here.
telnet_port: 6028

# Where to log telnet attempts if CSV logging is enabled
telnet_csv_name: "telnet_attempts.csv"

# Prompt shown before the hostname and login request.
# Impersonates an Ubuntu 22.04.3 LTS telnetd server by default.
telnet_login_prompt: "Ubuntu 22.04.3 LTS\r\n"

# Message sent to the attacker after they fail to log in on telnet.
telnet_message: "\r\nAccess denied.\r\n"

# Number of previous IPs to keep track of to avoid duplicate reports
ip_log: 30

# List of ports the port scan honeypot will listen on
portscan_ports: [6062, 6063, 6064]

# Where to log port scan attempts if CSV logging is enabled
portscan_csv_name: "portscan_attempts.csv"

# How many of the above ports must receive connections from the same IP before the honeypot reports it as a scanner
portscan_strikes: 3

# Port the fake SSH server will listen on.
# Beware, the standard port (22) may require root access!
# Alternatively, you could use iptables to redirect 22 to the port here.
ssh_port: 6222

# Where to log SSH attempts if CSV logging is enabled
ssh_csv_name: "ssh_attempts.csv"